import { expect, test, type Page } from '@playwright/test';
import { expectAccessible, expectHealthy, signIn, trackErrors } from './support';

async function stories(): Promise<Record<string, string>> {
  const r = await fetch('http://localhost:54399/__seed');
  return ((await r.json()) as { stories: Record<string, string> }).stories;
}

function isoDaysAgo(n: number) {
  const d = new Date(Date.now() - n * 864e5);
  return new Intl.DateTimeFormat('en-CA', { timeZone: 'America/New_York' }).format(d);
}

async function addMedication(page: Page, name: string, drugClass: string, daysAgo: number) {
  await page.getByRole('tab', { name: 'Medications' }).click();
  await page.getByRole('button', { name: 'Add medicine' }).click();
  const form = page.getByTestId('medication-form');
  await form.getByLabel('Medicine name').fill(name);
  await form.getByLabel('Drug class').selectOption(drugClass);
  await form.getByLabel('Dose amount').fill('25');
  await form.getByLabel('Times of day').fill('21:00');
  await form.getByLabel('Effective date').fill(isoDaysAgo(daysAgo));
  await form.getByRole('button', { name: 'Save' }).click();
  await expect(page.getByText('Medicine saved. The check-in will update.')).toBeVisible();
}

test('nurse: caseload, every patient tab, timeline highlight, review actions, summary PDF', async ({
  page,
}) => {
  const errors = trackErrors(page);
  const s = await stories();
  await signIn(page, 'nurse1@demo.medwatch');
  await expect(page).toHaveURL(/\/clinic$/);
  await expect(page.getByTestId('caseload-row')).toHaveCount(8);
  await expect(
    page.locator('[data-testid="caseload-row"][data-high="true"]').first(),
  ).toBeVisible();
  await expectAccessible(page, 'caseload');
  // sortable
  await page.getByRole('button', { name: 'Sort by Last check-in' }).click();
  await expectHealthy(page);

  await page.goto(`/clinic/patients/${s.story1}`);
  await expect(page.getByTestId('timeline')).toBeVisible();
  await expectAccessible(page, 'timeline');
  await page.getByTestId('timeline-flag').first().click();
  await expect(page.getByTestId('timeline-highlight')).toBeVisible();
  for (const r of ['7 days', '90 days']) await page.getByRole('button', { name: r }).click();

  for (const tab of ['Medications', 'Flags', 'Doses', 'Symptoms', 'Summary', 'People']) {
    await page.getByRole('tab', { name: tab }).click();
    await expectHealthy(page);
    await expectAccessible(page, tab);
  }

  // Flags: why + acknowledge + dismiss requires a reason
  await page.getByRole('tab', { name: 'Flags' }).click();
  const first = page.getByTestId('flag-card').first();
  await first.getByRole('button', { name: 'Why?' }).click();
  await expect(first.getByTestId('flag-evidence')).toBeVisible();
  await expectAccessible(page, 'flag evidence');
  await first.getByRole('button', { name: 'Acknowledge' }).click();
  await expect(page.getByText('Review saved.')).toBeVisible();
  const second = page
    .getByTestId('flag-card')
    .filter({ has: page.getByRole('button', { name: 'Dismiss' }) })
    .first();
  await second.getByRole('button', { name: 'Dismiss' }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Save note' }).click();
  await expect(page.getByRole('dialog').getByText('This field is required.')).toBeVisible();
  await page
    .getByRole('dialog')
    .getByLabel('Reason for dismissing (required)')
    .fill('Known and monitored.');
  await page.getByRole('dialog').getByRole('button', { name: 'Save note' }).click();
  await expect(page.getByText('Review saved.').first()).toBeVisible();

  // Doses: correct a dose
  await page.getByRole('tab', { name: 'Doses' }).click();
  await page.getByTestId('dose-row').first().getByRole('button', { name: 'Correct' }).click();
  await page.getByRole('dialog').getByLabel('Status').selectOption('skipped');
  await page.getByRole('dialog').getByLabel('Note').fill('Held by care team');
  await page.getByRole('dialog').getByRole('button', { name: 'Save' }).click();
  await expect(page.getByText('Saved.').first()).toBeVisible();

  // E2E 5: generate a visit summary PDF
  await page.getByRole('tab', { name: 'Summary' }).click();
  await expect(page.getByTestId('summary-view')).toBeVisible();
  await expect(page.getByTestId('summary-footer')).toHaveText(
    'Generated by MedWatch for clinician review. Not a diagnosis. Adherence is caregiver/patient-reported.',
  );
  const download = page.waitForEvent('download');
  await page.getByTestId('generate-summary').click();
  const file = await download;
  expect(file.suggestedFilename()).toMatch(/^visit-summary-\d{4}-\d{2}-\d{2}-[0-9a-f]{8}\.pdf$/);
  await expect(page.getByText('Summary saved.')).toBeVisible();

  // People: add a consent
  await page.getByRole('tab', { name: 'People' }).click();
  await expect(page.getByTestId('consent-row').first()).toBeVisible();
  const before = await page.getByTestId('consent-row').count();
  await page.getByRole('button', { name: 'Add consent' }).click();
  await page.getByRole('dialog').getByLabel('Granted by (name)').fill('Test Person');
  await page.getByRole('dialog').getByRole('button', { name: 'Save' }).click();
  await expect(page.getByTestId('consent-row')).toHaveCount(before + 1);

  await page.goto('/clinic/flags');
  await expect(page.getByRole('heading', { name: 'Flag inbox' })).toBeVisible();
  await expectAccessible(page, 'inbox');
  expect(errors).toEqual([]);
});

test('E2E 1b: a new medicine regenerates the check-in with a related question', async ({
  page,
}) => {
  const s = await stories();
  await signIn(page, 'nurse1@demo.medwatch');
  await page.goto(`/clinic/patients/${s.story2}?tab=medications`);
  await addMedication(page, 'Naproxen', 'nsaid', 0);
  const panel = page.getByTestId('template-panel');
  await expect(panel).toHaveAttribute('data-source', 'ai');
  await expect(panel.getByText(/Asked because of: .*Naproxen/).first()).toBeVisible();
});

test('E2E 3: medicine start → matching symptom → flag with evidence → acknowledge', async ({
  browser,
}) => {
  const s = await stories();
  const nurse = await browser.newPage();
  await signIn(nurse, 'nurse1@demo.medwatch');
  await nurse.goto(`/clinic/patients/${s.story2}?tab=medications`);
  await addMedication(nurse, 'Diphenhydramine', 'first_gen_antihistamine', 2);
  await expect(
    nurse.getByTestId('template-panel').locator('[data-symptom="drowsiness"]'),
  ).toBeVisible();

  // Caregiver logs drowsiness for the same patient (2 days after the start).
  const cg = await browser.newPage();
  await signIn(cg, 'caregiver1@demo.medwatch');
  await cg.goto(`/care/${s.story2}?tab=checkin`);
  await expect(cg.getByTestId('checkin-flow').or(cg.getByTestId('checkin-done'))).toBeVisible();
  if (await cg.getByTestId('checkin-done').isVisible())
    await cg.getByRole('button', { name: 'Change today’s answers' }).click();
  await cg.getByRole('radio', { name: /Okay/ }).first().click();
  for (let i = 0; i < 12; i++) {
    const q = cg.getByTestId('checkin-question');
    if (!(await q.isVisible().catch(() => false))) break;
    if ((await q.getAttribute('data-symptom')) === 'drowsiness') {
      await cg.getByRole('button', { name: 'Yes', exact: true }).click();
      await cg.getByRole('radio', { name: 'A lot' }).click();
    } else await cg.getByRole('button', { name: 'No', exact: true }).click();
  }
  await cg.getByRole('button', { name: 'Next' }).click();
  await cg.getByRole('button', { name: 'Send check-in' }).click();
  await expect(cg.getByTestId('checkin-done')).toBeVisible();

  await nurse.goto(`/clinic/patients/${s.story2}?tab=flags`);
  const flag = nurse
    .getByTestId('flag-card')
    .filter({ hasText: 'Drowsiness began after Diphenhydramine start' });
  await expect(flag).toBeVisible({ timeout: 15_000 });
  await expect(flag).toContainText('For clinician review.');
  await flag.getByRole('button', { name: 'Why?' }).click();
  await expect(flag.getByTestId('flag-evidence')).toContainText('Diphenhydramine');
  await flag.getByRole('button', { name: 'Acknowledge' }).click();
  await expect(nurse.getByText('Review saved.')).toBeVisible();
});
