/**
 * Visit summary builder (spec §7.4). Pure: returns structured content that the web app
 * renders as a one-page preview and PDF. Long lists are truncated with "+N more".
 */
import type {
  DoseEvent,
  FlagStatus,
  FlagType,
  IsoDate,
  Medication,
  MedicationChange,
  PatientInfo,
  Severity,
  SymptomCatalogEntry,
  SymptomLog,
} from './types.ts';
import type { RuleSet } from './rules/loader.ts';
import { drugClassLabel } from './rules/loader.ts';
import { SYMPTOM_CATALOG, symptomLabel } from './catalog.ts';
import { adherenceRate } from './adherence.ts';
import { ageOn } from './age.ts';
import { formatDose, isMedicationActiveOn } from './medications.ts';
import { addDays, formatLongDate, localDate, startOfLocalDay } from './time.ts';
import { SEVERITY_RANK } from './settings.ts';

export const SUMMARY_FOOTER =
  'Generated by MedWatch for clinician review. Not a diagnosis. Adherence is caregiver/patient-reported.';

export const SUMMARY_LIMITS = {
  changes: 6,
  medications: 12,
  adherence: 8,
  symptoms: 5,
  flags: 6,
  questions: 4,
} as const;

export interface Truncated<T> {
  rows: T[];
  more: number;
}

export interface SummaryFlagInput {
  id: string;
  flag_type: FlagType;
  severity: Severity;
  status: FlagStatus;
  title: string;
  created_at: string;
  reviewed_at?: string | null;
  review_note?: string | null;
  reviewer_name?: string | null;
}

export interface VisitSummaryInput {
  patient: PatientInfo;
  period: { start: IsoDate; end: IsoDate };
  generatedAt: Date | string;
  generatedBy: string;
  timezone: string;
  medications: readonly Medication[];
  medicationChanges: readonly MedicationChange[];
  doseEvents: readonly DoseEvent[];
  symptomLogs: readonly SymptomLog[];
  flags: readonly SummaryFlagInput[];
  rules: RuleSet;
  catalog?: readonly SymptomCatalogEntry[];
}

export type Trajectory = 'better' | 'same' | 'worse';

export interface VisitSummaryContent {
  version: 1;
  header: {
    patient_name: string;
    age: number;
    period_start: IsoDate;
    period_end: IsoDate;
    period_label: string;
    generated_at: string;
    generated_by: string;
  };
  medication_changes: Truncated<{
    date: IsoDate;
    medication: string;
    change: string;
    detail: string;
  }>;
  current_medications: Truncated<{
    name: string;
    dose: string;
    schedule: string;
    drug_class: string;
  }>;
  adherence: {
    overall: { rate: number | null; given: number; total: number; label: 'reported' };
    by_medication: Truncated<{
      medication: string;
      rate: number | null;
      given: number;
      total: number;
    }>;
  };
  symptoms: Truncated<{
    code: string;
    symptom: string;
    first_seen: IsoDate;
    days_reported: number;
    max_severity: number;
    trajectory: Trajectory;
  }>;
  flags: Truncated<{
    title: string;
    severity: Severity;
    status: FlagStatus;
    created: IsoDate;
    reviewer_note: string | null;
    reviewer: string | null;
  }>;
  questions: Truncated<string>;
  footer: string;
}

const CHANGE_LABEL: Record<MedicationChange['change_type'], string> = {
  started: 'Started',
  stopped: 'Stopped',
  dose_increased: 'Dose raised',
  dose_decreased: 'Dose lowered',
  schedule_changed: 'Schedule changed',
};

function truncate<T>(items: T[], limit: number): Truncated<T> {
  return { rows: items.slice(0, limit), more: Math.max(0, items.length - limit) };
}

function describeChange(c: MedicationChange): string {
  const dose = (v: Record<string, unknown> | null | undefined) =>
    v && v.dose_amount !== undefined && v.dose_amount !== null
      ? `${String(v.dose_amount)}${v.dose_unit ? ` ${String(v.dose_unit)}` : ''}`
      : '';
  const before = dose(c.previous);
  const after = dose(c.current);
  if (before && after && before !== after) return `${before} → ${after}`;
  if (after) return after;
  return '';
}

export function trajectoryOf(series: number[]): Trajectory {
  if (series.length < 2) return 'same';
  const mid = Math.floor(series.length / 2);
  const avg = (xs: number[]) => xs.reduce((s, x) => s + x, 0) / Math.max(1, xs.length);
  const first = avg(series.slice(0, mid));
  const second = avg(series.slice(mid));
  if (second - first >= 0.3) return 'worse';
  if (first - second >= 0.3) return 'better';
  return 'same';
}

const QUESTION_BY_TYPE: Record<FlagType, (title: string) => string> = {
  temporal_correlation: (t) => `${t}. Is this worth reviewing?`,
  medication_risk: (t) => `${t}: is this worth reviewing at this visit?`,
  interaction: (t) => `${t}: is this combination worth reviewing?`,
  adherence: (t) => `${t}: are there barriers to taking this medicine as planned?`,
};

export function buildVisitSummary(input: VisitSummaryInput): VisitSummaryContent {
  const catalog = input.catalog ?? SYMPTOM_CATALOG;
  const { start, end } = input.period;
  const tz = input.timezone;
  const periodStart = startOfLocalDay(start, tz);
  const periodEnd = startOfLocalDay(addDays(end, 1), tz);
  const generatedAt =
    typeof input.generatedAt === 'string' ? input.generatedAt : input.generatedAt.toISOString();
  const medName = new Map(input.medications.map((m) => [m.id, m.name]));

  // Medication changes in period
  const changes = input.medicationChanges
    .filter((c) => c.effective_date >= start && c.effective_date <= end)
    .sort((a, b) => b.effective_date.localeCompare(a.effective_date) || a.id.localeCompare(b.id))
    .map((c) => ({
      date: c.effective_date,
      medication: medName.get(c.medication_id) ?? 'Unknown medicine',
      change: CHANGE_LABEL[c.change_type],
      detail: describeChange(c),
    }));

  // Current medication list (as of period end)
  const current = input.medications
    .filter((m) => isMedicationActiveOn(m, end))
    .sort((a, b) => a.name.localeCompare(b.name))
    .map((m) => ({
      name: m.name,
      dose: formatDose(m),
      schedule: m.prn
        ? 'As needed'
        : (m.schedule_times ?? []).join(', ') || m.frequency_label || '',
      drug_class: drugClassLabel(input.rules, m.drug_class),
    }));

  // Adherence
  const now = generatedAt;
  const overall = adherenceRate(input.doseEvents, { start: periodStart, end: periodEnd }, now);
  const byMed = input.medications
    .map((m) => {
      const r = adherenceRate(
        input.doseEvents.filter((d) => d.medication_id === m.id),
        { start: periodStart, end: periodEnd },
        now,
      );
      return { medication: m.name, rate: r.rate, given: r.given, total: r.total };
    })
    .filter((r) => r.total > 0)
    .sort((a, b) => (a.rate ?? 1) - (b.rate ?? 1) || a.medication.localeCompare(b.medication));

  // Symptom trends
  const logs = input.symptomLogs
    .filter((l) => l.logged_for_date >= start && l.logged_for_date <= end)
    .sort((a, b) => a.logged_for_date.localeCompare(b.logged_for_date));
  const codes = new Set(
    logs.flatMap((l) => l.entries.filter((e) => e.severity > 0).map((e) => e.symptom_code)),
  );
  const symptoms = [...codes]
    .map((code) => {
      const series = logs.map((l) => l.entries.find((e) => e.symptom_code === code)?.severity ?? 0);
      const reported = logs.filter((l) =>
        l.entries.some((e) => e.symptom_code === code && e.severity > 0),
      );
      return {
        code,
        symptom: symptomLabel(code, catalog),
        first_seen: reported[0]!.logged_for_date,
        days_reported: reported.length,
        max_severity: Math.max(...series),
        trajectory: trajectoryOf(series),
      };
    })
    .sort(
      (a, b) =>
        b.days_reported - a.days_reported ||
        b.max_severity - a.max_severity ||
        a.symptom.localeCompare(b.symptom),
    );

  // Flags: open ones plus anything created or reviewed in the period
  const inPeriod = (iso: string | null | undefined) => {
    if (!iso) return false;
    const d = localDate(iso, tz);
    return d >= start && d <= end;
  };
  const flags = input.flags
    .filter((f) => f.status === 'open' || inPeriod(f.created_at) || inPeriod(f.reviewed_at))
    .sort(
      (a, b) =>
        Number(b.status === 'open') - Number(a.status === 'open') ||
        SEVERITY_RANK[b.severity] - SEVERITY_RANK[a.severity] ||
        b.created_at.localeCompare(a.created_at),
    );
  const questions = flags
    .filter((f) => f.status === 'open' || f.status === 'escalated')
    .map((f) => QUESTION_BY_TYPE[f.flag_type](f.title));

  return {
    version: 1,
    header: {
      patient_name: `${input.patient.first_name} ${input.patient.last_name}`,
      age: ageOn(input.patient.date_of_birth, localDate(generatedAt, tz)),
      period_start: start,
      period_end: end,
      period_label: `${formatLongDate(start)} – ${formatLongDate(end)}`,
      generated_at: generatedAt,
      generated_by: input.generatedBy,
    },
    medication_changes: truncate(changes, SUMMARY_LIMITS.changes),
    current_medications: truncate(current, SUMMARY_LIMITS.medications),
    adherence: {
      overall: {
        rate: overall.rate,
        given: overall.given,
        total: overall.total,
        label: 'reported',
      },
      by_medication: truncate(byMed, SUMMARY_LIMITS.adherence),
    },
    symptoms: truncate(symptoms, SUMMARY_LIMITS.symptoms),
    flags: truncate(
      flags.map((f) => ({
        title: f.title,
        severity: f.severity,
        status: f.status,
        created: localDate(f.created_at, tz),
        reviewer_note: f.review_note ?? null,
        reviewer: f.reviewer_name ?? null,
      })),
      SUMMARY_LIMITS.flags,
    ),
    questions: truncate(questions, SUMMARY_LIMITS.questions),
    footer: SUMMARY_FOOTER,
  };
}
