import { expect, test } from '@playwright/test';
import { hasBackend, users } from './support/env';
import { adminDb, expectAccessible, signIn } from './support/helpers';
import { addMedication, completeCheckin } from './support/nurse';
import { linkedPatientIds } from './support/data';

test.describe('nurse', () => {
  test.skip(!hasBackend, 'needs the cloud dev project (see PROGRESS.md)');

  // E2E 1b: a new medicine regenerates the patient's check-in with a related question.
  test('new medicine regenerates the tailored check-in', async ({ page }) => {
    const [patientId] = await linkedPatientIds(users.patient1);
    await signIn(page, users.nurse1);
    await page.goto(`/clinic/patients/${patientId}?tab=medications`);
    await addMedication(page, 'Naproxen', 'nsaid', 0);
    await expect(
      page
        .getByTestId('template-panel')
        .getByText(/Asked because of: .*Naproxen/)
        .first(),
    ).toBeVisible({ timeout: 30_000 });
  });

  // E2E 3: start a medicine, a matching symptom 2 days later (seeded date via effective date),
  // flag engine runs, nurse sees the flag with evidence and acknowledges it.
  test('medicine start → matching symptom → flag with evidence → acknowledge', async ({
    browser,
  }) => {
    const [patientId] = await linkedPatientIds(users.caregiver1);
    const nurse = await browser.newPage();
    await signIn(nurse, users.nurse1);
    await nurse.goto(`/clinic/patients/${patientId}?tab=medications`);
    await addMedication(nurse, 'Diphenhydramine', 'first_gen_antihistamine', 2);
    await expect(
      nurse.getByTestId('template-panel').locator('[data-symptom="drowsiness"]'),
    ).toBeVisible({ timeout: 30_000 });

    const cg = await browser.newPage();
    await signIn(cg, users.caregiver1);
    await cg.goto(`/care/${patientId}?tab=checkin`);
    const asked = await completeCheckin(cg, 'drowsiness');
    expect(asked).toContain('drowsiness');

    await nurse.goto(`/clinic/patients/${patientId}?tab=flags`);
    const flag = nurse
      .getByTestId('flag-card')
      .filter({ hasText: 'Drowsiness began after Diphenhydramine start' });
    await expect(async () => {
      await nurse.reload();
      await expect(flag).toBeVisible({ timeout: 2000 });
    }).toPass({ timeout: 60_000 });
    await flag.getByRole('button', { name: 'Why?' }).click();
    await expect(flag.getByTestId('flag-evidence')).toContainText('Diphenhydramine');
    await expectAccessible(nurse);
    await flag.getByRole('button', { name: 'Acknowledge' }).click();
    await expect(nurse.getByText('Review saved.')).toBeVisible();
    const { data } = await adminDb()
      .from('flags')
      .select('status, reviewed_by')
      .eq('patient_id', patientId)
      .ilike('title', 'Drowsiness began after Diphenhydramine%');
    expect(data?.[0]?.status).toBe('acknowledged');
  });

  // E2E 5: nurse generates a visit summary PDF.
  test('generates a visit summary PDF', async ({ page }) => {
    const [patientId] = await linkedPatientIds(users.patient1);
    await signIn(page, users.nurse1);
    await page.goto(`/clinic/patients/${patientId}?tab=summary`);
    await expect(page.getByTestId('summary-footer')).toHaveText(
      'Generated by MedWatch for clinician review. Not a diagnosis. Adherence is caregiver/patient-reported.',
    );
    await expectAccessible(page);
    const download = page.waitForEvent('download');
    await page.getByTestId('generate-summary').click();
    expect((await download).suggestedFilename()).toMatch(/^visit-summary-.*\.pdf$/);
    const { data } = await adminDb()
      .from('audit_log')
      .select('action, entity_type')
      .eq('action', 'export')
      .eq('entity_type', 'visit_summary')
      .limit(1);
    expect(data?.length).toBe(1);
  });

  test('caseload and flag inbox pass axe', async ({ page }) => {
    await signIn(page, users.nurse1);
    await expect(page.getByTestId('caseload-row').first()).toBeVisible();
    await expectAccessible(page);
    await page.goto('/clinic/flags');
    await expectAccessible(page);
  });
});
