// Synthetic, fictional reference data for the demo seed (Hard Rule 1).
// No real people: names are combined at random from generic lists; phone numbers use the
// reserved fictional 555-01xx range; emails use the non-routable demo.medwatch domain.

export const FIRST_NAMES = [
  'Margaret',
  'Harold',
  'Dorothy',
  'Walter',
  'Evelyn',
  'Franklin',
  'Bernice',
  'Gordon',
  'Ruth',
  'Raymond',
  'Helen',
  'Arthur',
  'Mildred',
  'Eugene',
  'Loretta',
  'Clarence',
  'Virginia',
  'Howard',
  'Irene',
  'Ralph',
  'Doris',
  'Leonard',
  'Gladys',
  'Vernon',
  'Shirley',
  'Herbert',
  'Norma',
  'Lloyd',
  'Phyllis',
  'Ernest',
] as const;

export const LAST_NAMES = [
  'Abernathy',
  'Birchwood',
  'Calloway',
  'Dunmore',
  'Ellsworth',
  'Fairbanks',
  'Greenleaf',
  'Hollister',
  'Ingleby',
  'Juniper',
  'Kettering',
  'Lindqvist',
  'Merriweather',
  'Northcott',
  'Oakhurst',
  'Pemberton',
  'Quimby',
  'Ravenscroft',
  'Stillwater',
  'Thistlewood',
  'Underhill',
  'Vandermeer',
  'Whitlock',
  'Yarrow',
  'Ashdown',
  'Brightwater',
  'Copperfield',
  'Dewberry',
] as const;

export interface FormularyItem {
  name: string;
  generic_name: string;
  drug_class: string;
  dose_amount: number;
  dose_unit: string;
  route: string;
  schedule_times: string[];
  frequency_label: string;
  purpose: string;
  prn?: boolean;
}

const daily = (t: string) => ({ schedule_times: [t], frequency_label: 'Once daily' });
const twice = (a: string, b: string) => ({
  schedule_times: [a, b],
  frequency_label: 'Twice daily',
});

/** Generic medicine names only; dosing is illustrative, not a recommendation. */
export const FORMULARY: Record<string, FormularyItem> = {
  atorvastatin: {
    name: 'Atorvastatin',
    generic_name: 'atorvastatin',
    drug_class: 'statin',
    dose_amount: 20,
    dose_unit: 'mg',
    route: 'oral',
    ...daily('20:00'),
    purpose: 'Cholesterol',
  },
  lisinopril: {
    name: 'Lisinopril',
    generic_name: 'lisinopril',
    drug_class: 'ace_inhibitor',
    dose_amount: 10,
    dose_unit: 'mg',
    route: 'oral',
    ...daily('08:00'),
    purpose: 'Blood pressure',
  },
  amlodipine: {
    name: 'Amlodipine',
    generic_name: 'amlodipine',
    drug_class: 'calcium_channel_blocker',
    dose_amount: 5,
    dose_unit: 'mg',
    route: 'oral',
    ...daily('08:00'),
    purpose: 'Blood pressure',
  },
  metoprolol: {
    name: 'Metoprolol succinate',
    generic_name: 'metoprolol',
    drug_class: 'beta_blocker',
    dose_amount: 25,
    dose_unit: 'mg',
    route: 'oral',
    ...daily('08:00'),
    purpose: 'Heart rate and blood pressure',
  },
  hydrochlorothiazide: {
    name: 'Hydrochlorothiazide',
    generic_name: 'hydrochlorothiazide',
    drug_class: 'thiazide_diuretic',
    dose_amount: 12.5,
    dose_unit: 'mg',
    route: 'oral',
    ...daily('08:00'),
    purpose: 'Water pill',
  },
  furosemide: {
    name: 'Furosemide',
    generic_name: 'furosemide',
    drug_class: 'loop_diuretic',
    dose_amount: 20,
    dose_unit: 'mg',
    route: 'oral',
    ...daily('08:00'),
    purpose: 'Water pill',
  },
  metformin: {
    name: 'Metformin',
    generic_name: 'metformin',
    drug_class: 'biguanide',
    dose_amount: 500,
    dose_unit: 'mg',
    route: 'oral',
    ...twice('08:00', '18:00'),
    purpose: 'Blood sugar',
  },
  levothyroxine: {
    name: 'Levothyroxine',
    generic_name: 'levothyroxine',
    drug_class: 'thyroid_hormone',
    dose_amount: 50,
    dose_unit: 'mcg',
    route: 'oral',
    ...daily('06:30'),
    purpose: 'Thyroid',
  },
  vitamin_d: {
    name: 'Vitamin D3',
    generic_name: 'cholecalciferol',
    drug_class: 'vitamin_supplement',
    dose_amount: 1000,
    dose_unit: 'IU',
    route: 'oral',
    ...daily('08:00'),
    purpose: 'Bone health',
  },
  calcium: {
    name: 'Calcium carbonate',
    generic_name: 'calcium carbonate',
    drug_class: 'vitamin_supplement',
    dose_amount: 500,
    dose_unit: 'mg',
    route: 'oral',
    ...daily('12:00'),
    purpose: 'Bone health',
  },
  omeprazole: {
    name: 'Omeprazole',
    generic_name: 'omeprazole',
    drug_class: 'ppi',
    dose_amount: 20,
    dose_unit: 'mg',
    route: 'oral',
    ...daily('07:30'),
    purpose: 'Stomach acid',
  },
  aspirin: {
    name: 'Aspirin (low dose)',
    generic_name: 'aspirin',
    drug_class: 'antiplatelet',
    dose_amount: 81,
    dose_unit: 'mg',
    route: 'oral',
    ...daily('08:00'),
    purpose: 'Heart',
  },
  sertraline: {
    name: 'Sertraline',
    generic_name: 'sertraline',
    drug_class: 'ssri',
    dose_amount: 50,
    dose_unit: 'mg',
    route: 'oral',
    ...daily('08:00'),
    purpose: 'Mood',
  },
  tamsulosin: {
    name: 'Tamsulosin',
    generic_name: 'tamsulosin',
    drug_class: 'alpha_blocker',
    dose_amount: 0.4,
    dose_unit: 'mg',
    route: 'oral',
    ...daily('21:00'),
    purpose: 'Urination',
  },
  gabapentin: {
    name: 'Gabapentin',
    generic_name: 'gabapentin',
    drug_class: 'gabapentinoid',
    dose_amount: 100,
    dose_unit: 'mg',
    route: 'oral',
    ...twice('08:00', '20:00'),
    purpose: 'Nerve pain',
  },
  donepezil: {
    name: 'Donepezil',
    generic_name: 'donepezil',
    drug_class: 'other',
    dose_amount: 5,
    dose_unit: 'mg',
    route: 'oral',
    ...daily('21:00'),
    purpose: 'Memory',
  },
  docusate: {
    name: 'Docusate',
    generic_name: 'docusate',
    drug_class: 'other',
    dose_amount: 100,
    dose_unit: 'mg',
    route: 'oral',
    ...daily('08:00'),
    purpose: 'Bowel regularity',
  },
  multivitamin: {
    name: 'Multivitamin',
    generic_name: 'multivitamin',
    drug_class: 'vitamin_supplement',
    dose_amount: 1,
    dose_unit: 'tablet',
    route: 'oral',
    ...daily('08:00'),
    purpose: 'Supplement',
  },
  carvedilol: {
    name: 'Carvedilol',
    generic_name: 'carvedilol',
    drug_class: 'beta_blocker',
    dose_amount: 6.25,
    dose_unit: 'mg',
    route: 'oral',
    ...twice('08:00', '20:00'),
    purpose: 'Heart',
  },
  acetaminophen: {
    name: 'Acetaminophen',
    generic_name: 'acetaminophen',
    drug_class: 'other',
    dose_amount: 500,
    dose_unit: 'mg',
    route: 'oral',
    schedule_times: [],
    frequency_label: 'As needed',
    purpose: 'Pain',
    prn: true,
  },
  diphenhydramine: {
    name: 'Diphenhydramine',
    generic_name: 'diphenhydramine',
    drug_class: 'first_gen_antihistamine',
    dose_amount: 25,
    dose_unit: 'mg',
    route: 'oral',
    ...daily('21:00'),
    purpose: 'Sleep',
  },
  // story medicines
  zolpidem: {
    name: 'Zolpidem',
    generic_name: 'zolpidem',
    drug_class: 'sedative_hypnotic',
    dose_amount: 5,
    dose_unit: 'mg',
    route: 'oral',
    ...daily('21:00'),
    purpose: 'Sleep',
  },
  apixaban: {
    name: 'Apixaban',
    generic_name: 'apixaban',
    drug_class: 'anticoagulant',
    dose_amount: 2.5,
    dose_unit: 'mg',
    route: 'oral',
    ...twice('08:00', '20:00'),
    purpose: 'Prevent blood clots',
  },
  ibuprofen: {
    name: 'Ibuprofen',
    generic_name: 'ibuprofen',
    drug_class: 'nsaid',
    dose_amount: 400,
    dose_unit: 'mg',
    route: 'oral',
    ...daily('12:00'),
    purpose: 'Joint pain',
  },
  oxybutynin: {
    name: 'Oxybutynin',
    generic_name: 'oxybutynin',
    drug_class: 'anticholinergic',
    dose_amount: 5,
    dose_unit: 'mg',
    route: 'oral',
    ...daily('08:00'),
    purpose: 'Bladder',
  },
};

/** Background medicines (mostly lower-risk classes so the demo is not swamped with flags). */
export const BACKGROUND_POOL = [
  'atorvastatin',
  'lisinopril',
  'amlodipine',
  'metoprolol',
  'hydrochlorothiazide',
  'furosemide',
  'metformin',
  'levothyroxine',
  'vitamin_d',
  'calcium',
  'omeprazole',
  'aspirin',
  'sertraline',
  'tamsulosin',
  'gabapentin',
  'donepezil',
  'docusate',
  'multivitamin',
  'carvedilol',
  'acetaminophen',
  'diphenhydramine',
] as const;

/** Classes that should not appear twice for one patient. */
export const ONE_PER_CLASS = new Set([
  'statin',
  'beta_blocker',
  'calcium_channel_blocker',
  'ace_inhibitor',
]);

export const STAFF = {
  admin: { email: 'admin@demo.medwatch', full_name: 'Dana Whitfield (Demo)', role: 'agency_admin' },
  nurse1: { email: 'nurse1@demo.medwatch', full_name: 'Priya Natarajan, RN (Demo)', role: 'nurse' },
  nurse2: { email: 'nurse2@demo.medwatch', full_name: 'Marcus Bell, RN (Demo)', role: 'nurse' },
  nurse3: { email: 'nurse3@demo.medwatch', full_name: 'Elena Ruiz, RN (Demo)', role: 'nurse' },
  caregiver1: {
    email: 'caregiver1@demo.medwatch',
    full_name: 'Sam Hollis (Demo caregiver)',
    role: 'caregiver',
  },
  caregiver2: {
    email: 'caregiver2@demo.medwatch',
    full_name: 'Riley Brooks (Demo caregiver)',
    role: 'caregiver',
  },
} as const;

export const DEMO_PASSWORD = 'Demo!2345';
export const DEMO_ORG_NAME = 'Riverbend Home Health (Demo)';
export const DEMO_EMAIL_DOMAIN = 'demo.medwatch';
