export const adminCopy = {
  dashboardTitle: 'Agency dashboard',
  dashboardSubtitle: 'Who needs attention today, and how the agency is doing.',
  needsAttention: 'Needs attention today',
  needsAttentionEmpty: 'Nobody needs extra attention right now.',
  reasons: {
    high: (n: number) => (n === 1 ? '1 high flag open' : `${n} high flags open`),
    escalation: (n: number) =>
      n === 1 ? '1 dose escalated in the last day' : `${n} doses escalated in the last day`,
    noCheckin: (d: string | null) => (d ? `No check-in since ${d}` : 'No check-ins yet'),
  },
  kpi: {
    active: 'Active clients',
    adherence: 'Doses taken, last 7 days (reported)',
    openFlags: 'Open flags',
    openFlagsHint: (h: number, m: number, l: number) => `${h} high · ${m} medium · ${l} low`,
    review: 'Median time to review a flag',
    reviewHint: (n: number) => `Last 30 days, ${n} reviewed`,
    hours: (h: number) => `${h} h`,
    checkins: 'Check-in completion, last 7 days',
  },
  adherenceTrend: 'Reported adherence, last 30 days',
  flagsWeekly: 'Flags created vs reviewed per week',
  created: 'Created',
  reviewed: 'Reviewed',
  aiCard: 'AI check-ins',
  aiShare: (ai: number, total: number) => `${ai} of ${total} active check-ins tailored with AI`,
  aiFailures: (failed: number, total: number) =>
    total
      ? `${failed} of ${total} AI requests failed in the last 7 days (fell back to rules)`
      : 'No AI requests in the last 7 days',
  aiOff: 'When AI is off or fails, clients get the rules-based check-in.',
  // patients
  patientsTitle: 'Clients',
  addPatient: 'Add client',
  showDischarged: 'Show discharged clients',
  status: { active: 'Active', discharged: 'Discharged' },
  patientForm: {
    first: 'First name',
    last: 'Last name',
    dob: 'Date of birth',
    nurse: 'Primary nurse',
    noNurse: 'Not assigned',
    notes: 'Notes (optional)',
    consentTitle: 'Data-use consent (required)',
    consentBy: 'Consent given by (name)',
    consentRel: 'Relationship to client',
    consentVersion: 'Consent document version',
    consentConfirm: 'I confirm the signed data-use consent is on file.',
    consentRequired: 'Record the data-use consent before adding a client.',
    save: 'Add client',
  },
  patientAdded: 'Client added.',
  manage: 'Manage',
  manageTitle: (name: string) => `Manage ${name}`,
  caseload: 'Caseload (nurses)',
  caseloadHint: 'Nurses who can see and manage this client.',
  saveCaseload: 'Save caseload',
  caseloadSaved: 'Caseload saved.',
  primaryNurse: 'Primary nurse',
  caregivers: 'Linked caregivers',
  linkCaregiver: 'Link existing caregiver',
  link: 'Link',
  unlink: 'Unlink',
  inviteCaregiver: 'Invite a caregiver by email',
  invitePatient: 'Invite this client to use the app',
  inviteRoles: { caregiver: 'Caregiver', patient: 'Client (app user)' },
  statusCol: 'Status',
  discharge: 'Discharge',
  dischargeTitle: 'Discharge this client',
  dischargeBody: 'Discharged clients keep their records but leave active lists and jobs.',
  reactivate: 'Reactivate',
  exportJson: 'Export all data (JSON)',
  exported: 'Export downloaded and logged.',
  deleteTitle: 'Permanently delete this client',
  deleteBody:
    'This removes the client and all of their records. It cannot be undone. The deletion is written to the audit log.',
  deleteConfirmLabel: (word: string) => `Type ${word} to confirm`,
  deleteWord: 'DELETE',
  deleteButton: 'Delete permanently',
  deleted: 'Client deleted.',
  saved: 'Saved.',
  // team
  teamTitle: 'Team',
  invite: 'Invite user',
  inviteTitle: 'Invite a user',
  email: 'Email',
  role: 'Role',
  fullName: 'Full name',
  patientFor: 'Client (for caregivers and clients)',
  sendInvite: 'Send invitation',
  inviteSent: 'Invitation sent.',
  inviteFailed: 'The invitation could not be sent. The email may already have an account.',
  pendingInvites: 'Pending invitations',
  noInvites: 'No pending invitations.',
  expires: (d: string) => `Expires ${d}`,
  revokeInvite: 'Revoke',
  cols: {
    name: 'Name',
    email: 'Email',
    role: 'Role',
    mfa: 'Require MFA',
    active: 'Active',
    actions: 'Actions',
  },
  deactivate: 'Deactivate',
  activeLabel: 'Active',
  inactiveLabel: 'Inactive',
  activate: 'Activate',
  you: '(you)',
  // settings
  settingsTitle: 'Settings',
  settingsSaved: 'Settings saved.',
  timezone: 'Agency time zone',
  settingsFields: {
    missed_dose_grace_minutes: {
      label: 'Missed-dose grace period (minutes)',
      help: 'How long after a scheduled time a dose is marked missed and caregivers are alerted.',
    },
    agency_escalation_minutes: {
      label: 'Escalation threshold (minutes)',
      help: 'If a dose is still not confirmed this long after its scheduled time, the nurse and admins are alerted.',
    },
    flag_min_severity_for_alert: {
      label: 'Alert the care team for flags at or above',
      help: 'Flags below this severity still appear in lists but do not send an alert.',
    },
    flag_dedupe_hours: {
      label: 'Flag repeat window (hours)',
      help: 'A flag with the same cause is not raised again within this many hours.',
    },
    session_timeout_minutes: {
      label: 'Sign out after inactivity (minutes)',
      help: 'Users see a warning one minute before they are signed out.',
    },
  },
  // audit
  auditTitle: 'Audit log',
  auditSubtitle: 'Every view, change and export of client data. The log cannot be edited.',
  filters: {
    user: 'User',
    patient: 'Client',
    action: 'Action',
    from: 'From',
    to: 'To',
    any: 'Any',
  },
  exportCsv: 'Export CSV',
  auditCols: { when: 'When', user: 'User', action: 'Action', entity: 'Record', detail: 'Detail' },
  noAudit: 'No audit entries match these filters.',
  system: 'System',
  showing: (n: number) => `Showing the latest ${n} entries`,
  actions: {
    view: 'View',
    create: 'Create',
    update: 'Update',
    delete: 'Delete',
    export: 'Export',
    login: 'Sign in',
  },
  // pilot
  pilotTitle: 'Pilot metrics',
  pilotSubtitle: 'Outcomes for a date range. Adherence is caregiver/patient-reported.',
  pilotReport: 'Printable pilot report',
  print: 'Print',
  metrics: {
    flagsCreated: 'Flags raised',
    flagsReviewed: 'Flags reviewed',
    medianReview: 'Median time to review',
    escalated: 'Flags escalated',
    adherence: 'Reported adherence',
    checkins: 'Check-in completion',
    missedAlerts: 'Missed-dose alerts sent',
    escalationAlerts: 'Escalation alerts sent',
    byType: 'Flags by type and severity',
  },
  type: 'Type',
  severity: 'Severity',
  count: 'Count',
  reportTitle: 'MedWatch pilot report',
  reportFooter:
    'Synthetic demo data. Flags are prompts for clinician review only; they are not medical advice.',
  period: (a: string, b: string) => `${a} – ${b}`,
};
