export const authCopy = {
  signInTitle: 'Sign in to MedWatch',
  signInSubtitle: 'Medication safety for home health teams.',
  email: 'Email',
  password: 'Password',
  signIn: 'Sign in',
  signingIn: 'Signing in…',
  forgot: 'Forgot your password?',
  signInFailed: 'That email and password did not match. Please try again.',
  timedOut: 'You were signed out after a period of inactivity.',
  signedOut: 'You are now signed out.',
  forgotTitle: 'Reset your password',
  forgotBody: 'Enter your email and we will send you a link to set a new password.',
  sendLink: 'Send reset link',
  linkSent: 'If that email has an account, a reset link is on its way.',
  backToSignIn: 'Back to sign in',
  resetTitle: 'Choose a new password',
  newPassword: 'New password',
  confirmPassword: 'Confirm new password',
  passwordRule: 'At least 10 characters, with a letter and a number.',
  passwordsMismatch: 'The passwords do not match.',
  passwordWeak: 'Use at least 10 characters, including a letter and a number.',
  savePassword: 'Save password',
  passwordSaved: 'Your password has been updated.',
  resetLinkInvalid: 'This reset link has expired. Please request a new one.',
  mfaEnrollTitle: 'Set up two-step sign-in',
  mfaEnrollBody:
    'Your agency requires a second step for staff accounts. Scan this code with an authenticator app, then enter the 6-digit code it shows.',
  mfaSecretLabel: 'Or enter this key in your app:',
  mfaCode: '6-digit code',
  mfaVerify: 'Verify',
  mfaChallengeTitle: 'Enter your code',
  mfaChallengeBody: 'Open your authenticator app and enter the 6-digit code for MedWatch.',
  mfaInvalid: 'That code did not work. Check the time on your device and try again.',
  mfaQrAlt: 'QR code for your authenticator app',
  acceptTitle: 'Welcome to MedWatch',
  acceptBody: 'Finish setting up your account.',
  fullName: 'Your full name',
  acceptButton: 'Finish setup',
  acceptMissingToken:
    'This invitation link is missing its code. Ask your agency to send a new invitation.',
  acceptNeedsSession:
    'Open the invitation link from your email on this device to continue. The link signs you in for this step.',
  acceptFailed: 'We could not accept this invitation. It may have expired or already been used.',
  noProfileTitle: 'Your account is not set up yet',
  noProfileBody: 'Ask your agency administrator to send you an invitation.',
  signOut: 'Sign out',
  timeoutTitle: 'Are you still there?',
  timeoutBody: (s: number) => `For privacy, you will be signed out in ${s} seconds.`,
  staySignedIn: 'Stay signed in',
};
