export const checkinCopy = {
  title: 'How are you today?',
  titleFor: (name: string) => `How is ${name} today?`,
  intro: 'A few quick questions. It takes about 30 seconds.',
  feelingQuestion: 'Overall, how are you feeling today?',
  feelingQuestionFor: (name: string) => `Overall, how is ${name} feeling today?`,
  feelings: ['Very bad', 'Not good', 'Okay', 'Good', 'Very good'],
  feelingFaces: ['😣', '🙁', '😐', '🙂', '😄'],
  howMuch: 'How much?',
  severity: ['A little', 'Some', 'A lot'],
  stepOf: (i: number, n: number) => `Question ${i} of ${n}`,
  anythingElse: 'Anything else bothering you?',
  anythingElseFor: (name: string) => `Anything else bothering ${name}?`,
  pickAny: 'Tap anything that applies, then choose how much.',
  noteLabel: 'Anything you want the nurse to know? (optional)',
  noteHint: 'Please do not include other people’s names.',
  submit: 'Send check-in',
  sending: 'Sending…',
  thanks: 'Thank you!',
  thanksBody: 'Your check-in was sent to your care team.',
  thanksBodyFor: (name: string) => `The check-in for ${name} was sent to the care team.`,
  alreadyDone: 'Today’s check-in is done.',
  editToday: 'Change today’s answers',
  start: 'Start',
  failed: 'That did not send. Please try again.',
  youReported: 'You told us about:',
  nothingReported: 'No symptoms reported.',
  callNote: 'If something feels urgent, call your care team or 911.',
  back: 'Back',
  next: 'Next',
  skip: 'Skip',
};
