export const common = {
  appName: 'MedWatch',
  demoBanner: 'Demo environment — synthetic data only. Not for clinical use.',
  forClinicianReview: 'For clinician review.',
  loading: 'Loading…',
  genericError: 'Something went wrong. Please try again.',
  retry: 'Try again',
  save: 'Save',
  saving: 'Saving…',
  cancel: 'Cancel',
  close: 'Close',
  confirm: 'Confirm',
  back: 'Back',
  next: 'Next',
  done: 'Done',
  edit: 'Edit',
  remove: 'Remove',
  yes: 'Yes',
  no: 'No',
  none: 'None',
  notSet: 'Not set',
  skipToContent: 'Skip to main content',
  configErrorTitle: 'MedWatch is not configured',
  configErrorBody:
    'Some settings are missing. Ask your administrator to set these environment variables:',
  notFoundTitle: 'Page not found',
  notFoundBody: 'We could not find that page.',
  goHome: 'Go to home',
  forbiddenTitle: 'No access',
  forbiddenBody: 'You do not have access to this page.',
};
