export const doseCopy = {
  todayTitle: 'Today',
  todayFor: (name: string) => `Today for ${name}`,
  progress: (done: number, total: number) => `${done} of ${total} done`,
  remaining: (n: number) => (n === 1 ? '1 medicine still to take' : `${n} medicines still to take`),
  allDone: 'All done for today. Nice work!',
  noneToday: 'No medicines are scheduled for today.',
  tookIt: 'I took it',
  gaveIt: 'Given',
  notTaken: 'Not taken',
  undo: 'Undo',
  taken: 'Taken',
  notTakenDone: 'Not taken',
  missed: 'Missed',
  pending: 'Not yet',
  skipped: 'Skipped',
  dueAt: (time: string) => `Due ${time}`,
  takenAt: (time: string) => `Taken at ${time}`,
  confirmedByCaregiver: 'Confirmed by caregiver',
  confirmedByPatient: 'Confirmed by client',
  confirmedByNurse: 'Confirmed by nurse',
  reported: 'Reported',
  verified: 'Verified',
  notTakenTitle: 'Not taken',
  notTakenBody: 'You can add a reason. This helps the nurse understand.',
  reason: 'Reason (optional)',
  reasonOptions: ['Felt unwell', 'Ran out', 'Forgot', 'Chose not to', 'Other'],
  save: 'Save',
  saved: 'Saved.',
  saveFailed: 'That did not save. Please try again.',
  status: {
    pending: 'Not yet',
    given: 'Taken',
    missed: 'Missed',
    skipped: 'Skipped',
    refused: 'Not taken',
  },
  historyTitle: 'Dose history',
  correct: 'Correct',
  correctTitle: 'Correct this dose',
  newStatus: 'Status',
  note: 'Note',
  noteHint:
    'A note on a skipped dose (for example a hold from the care team) excuses it from adherence.',
  verify: 'Mark as verified by nurse',
  from: 'From',
  to: 'To',
  statusFilter: 'Status',
  all: 'All',
  medicine: 'Medicine',
  scheduled: 'Scheduled',
  confirmed: 'Confirmed',
  noDoses: 'No doses in this period.',
  method: 'Confirmed by',
};
