import type { FlagStatus, FlagType, Severity } from '@medwatch/core';

export const flagCopy = {
  severity: { high: 'High', medium: 'Medium', low: 'Low' } satisfies Record<Severity, string>,
  status: {
    open: 'Open',
    acknowledged: 'Acknowledged',
    dismissed: 'Dismissed',
    escalated: 'Escalated',
  } satisfies Record<FlagStatus, string>,
  type: {
    temporal_correlation: 'Symptom after a medicine change',
    medication_risk: 'Medicine risk',
    interaction: 'Medicine combination',
    adherence: 'Missed doses',
  } satisfies Record<FlagType, string>,
  why: 'Why?',
  hideWhy: 'Hide details',
  forReview: 'For clinician review',
  evidenceChange: 'Medicine change',
  evidenceDoses: 'Doses counted',
  evidenceSymptoms: 'Check-ins compared',
  evidenceRule: 'Rule',
  evidenceScore: 'How the score was built',
  evidenceOtherChanges: 'Other recent changes considered',
  evidenceMedicines: 'Medicines involved',
  points: (n: number) => `${n > 0 ? '+' : ''}${n}`,
  total: 'Total score',
  acknowledge: 'Acknowledge',
  dismiss: 'Dismiss',
  escalate: 'Escalate',
  dismissTitle: 'Dismiss this flag',
  dismissReason: 'Reason for dismissing (required)',
  escalateTitle: 'Escalate this flag',
  escalateNote: 'Note for the escalation (required)',
  addNote: 'Add a note',
  note: 'Note',
  saveNote: 'Save note',
  required: 'This field is required.',
  reviewedBy: (name: string, when: string) => `Reviewed by ${name} on ${when}`,
  reviewed: 'Review saved.',
  noFlags: 'No flags right now.',
  noFlagsBody: 'Flags appear here when MedWatch notices something worth a clinician’s review.',
  inboxTitle: 'Flag inbox',
  inboxSubtitle: 'Open flags across your caseload, most severe first.',
  readOnlyNote: 'Flags are prompts for the care team to review. They are not medical advice.',
  created: 'Raised',
  patient: 'Client',
  filterStatus: 'Status',
  allOpen: 'Open and acknowledged',
  all: 'All',
  showOnTimeline: 'Show on timeline',
  placeholderRules: 'Rules are placeholders that still need clinical review.',
};
