export const navCopy = {
  mainNav: 'Main',
  patient: { today: 'Today', checkin: 'How are you?', medicines: 'My medicines' },
  caregiver: { people: 'My people', alerts: 'Alerts' },
  nurse: { caseload: 'My caseload', inbox: 'Flag inbox' },
  admin: {
    dashboard: 'Dashboard',
    caseload: 'All clients',
    inbox: 'Flag inbox',
    patients: 'Clients',
    team: 'Team',
    settings: 'Settings',
    audit: 'Audit log',
    pilot: 'Pilot metrics',
  },
  footer: { privacy: 'Privacy policy', terms: 'Terms of use', about: 'About the flags' },
  alerts: 'Alerts',
  alertsUnread: (n: number) => (n === 1 ? '1 unread alert' : `${n} unread alerts`),
  alertsEmpty: 'No alerts.',
  markRead: 'Mark read',
  markAllRead: 'Mark all read',
  alertType: {
    missed_dose: 'Missed dose',
    flag: 'New flag for review',
    escalation: 'Dose still not confirmed',
  },
  openMenu: 'Open menu',
  closeMenu: 'Close menu',
  signedInAs: (name: string) => `Signed in as ${name}`,
  role: {
    patient: 'Client',
    caregiver: 'Caregiver',
    nurse: 'Nurse',
    agency_admin: 'Agency admin',
  },
};
