export const nurseCopy = {
  caseloadTitle: 'My caseload',
  allClientsTitle: 'All clients',
  caseloadSubtitle: 'Sorted by open flag severity. Select a column heading to sort.',
  noPatients: 'No clients on this caseload yet.',
  cols: {
    name: 'Client',
    age: 'Age',
    flags: 'Open flags',
    adherence: 'Doses taken (7 days, reported)',
    lastCheckin: 'Last check-in',
    lastVisit: 'Last visit',
    nurse: 'Primary nurse',
  },
  sortBy: (label: string) => `Sort by ${label}`,
  never: 'Never',
  today: 'Today',
  highFlagRow: 'Has a high flag',
  noFlags: 'None',
  flagCounts: (h: number, m: number, l: number) =>
    [h ? `${h} high` : '', m ? `${m} medium` : '', l ? `${l} low` : ''].filter(Boolean).join(', '),
  // patient detail
  tabs: {
    overview: 'Timeline',
    medications: 'Medications',
    flags: 'Flags',
    doses: 'Doses',
    symptoms: 'Symptoms',
    summary: 'Summary',
    people: 'People',
  },
  header: {
    age: (n: number) => `Age ${n}`,
    primaryNurse: (name: string) => `Primary nurse: ${name}`,
    noNurse: 'No primary nurse',
    activeMeds: 'Active medicines',
    openFlags: 'Open flags',
    adherence: 'Doses taken (7 days)',
    lastCheckin: 'Last check-in',
    discharged: 'Discharged',
  },
  // timeline
  timelineTitle: 'Timeline',
  range: 'Range',
  rangeDays: (n: number) => `${n} days`,
  laneChanges: 'Medicine changes',
  laneAdherence: 'Doses per day (reported)',
  laneSymptoms: 'Symptoms (0 none – 3 a lot)',
  given: 'Taken',
  missed: 'Missed',
  notTaken: 'Not taken',
  flagsInRange: 'Flags in this period — select one to highlight its evidence',
  clearHighlight: 'Clear highlight',
  noChanges: 'No medicine changes in this period.',
  noSymptoms: 'No symptoms reported in this period.',
  chartSummary: (changes: number, symptoms: string) =>
    `${changes} medicine changes. Symptoms shown: ${symptoms || 'none'}.`,
  // medications
  addMedication: 'Add medicine',
  editMedication: 'Change medicine',
  stopMedication: 'Stop medicine',
  stop: 'Stop',
  edit: 'Change',
  activeMeds: 'Active medicines',
  stoppedMeds: 'Stopped medicines',
  noMeds: 'No medicines yet.',
  medForm: {
    name: 'Medicine name',
    generic: 'Generic name',
    drugClass: 'Drug class',
    drugClassHint: 'Used by the flag rules. Choose “Other” if unsure.',
    purpose: 'What it is for',
    doseAmount: 'Dose amount',
    doseUnit: 'Dose unit',
    route: 'Route',
    frequency: 'Frequency label',
    times: 'Times of day',
    timesHint: '24-hour times separated by commas, e.g. 08:00, 20:00',
    timesInvalid: 'Use HH:MM times separated by commas.',
    prn: 'As needed (no schedule)',
    startDate: 'Start date',
    orderingClinician: 'Ordering clinician',
    changeType: 'Type of change',
    effectiveDate: 'Effective date',
    required: 'Required',
    save: 'Save',
  },
  changeTypes: {
    dose_increased: 'Dose raised',
    dose_decreased: 'Dose lowered',
    schedule_changed: 'Schedule or other change',
  },
  stopBody:
    'The medicine will be marked stopped from this date. This is recorded in the medicine history.',
  medSaved: 'Medicine saved. The check-in will update.',
  medFailed: 'That did not save. Please check the form and try again.',
  history: 'Change history',
  noHistory: 'No changes recorded.',
  // template
  templateTitle: 'Daily check-in for this client',
  templateSource: { ai: 'Tailored with AI', rules: 'Built from rules', default: 'Standard' },
  templateMade: (when: string) => `Made ${when}`,
  askedBecause: (names: string) => `Asked because of: ${names}`,
  core: 'Asked of everyone',
  regenerate: 'Regenerate check-in',
  regenerated: 'Check-in regenerated.',
  regenerateFailed: 'Could not regenerate right now. The current check-in stays in place.',
  noTemplate: 'No tailored check-in yet. The client sees the standard rules-based questions.',
  // symptoms
  symptomHistory: 'Check-in history',
  feeling: 'Feeling',
  reported: 'Reported',
  note: 'Note',
  noLogs: 'No check-ins in this period.',
  trendFor: 'Trend for',
  trendTitle: 'Symptom trend',
  // people
  caregivers: 'Linked people',
  noCaregivers: 'No caregivers linked.',
  consents: 'Consents on file',
  noConsents: 'No consents recorded.',
  addConsent: 'Add consent',
  revoke: 'Revoke',
  revoked: (d: string) => `Revoked ${d}`,
  consentTypes: {
    data_use: 'Data use',
    sms: 'Text messages',
    caregiver_access: 'Caregiver access',
  },
  consentForm: {
    type: 'Consent type',
    grantedBy: 'Granted by (name)',
    relationship: 'Relationship to client',
    version: 'Document version',
  },
  relationshipSelf: 'Self',
  relationshipCaregiver: 'Caregiver',
  consentSaved: 'Consent saved.',
  // inbox
  inboxEmpty: 'No open flags. Nice work.',
  openClient: 'Open client',
};
