export const summaryCopy = {
  title: 'Visit summary',
  latest: 'Latest visit summary',
  none: 'No visit summary yet.',
  noneBody: 'The nurse creates one at each visit.',
  download: 'Download PDF',
  downloading: 'Preparing PDF…',
  generate: 'Generate summary',
  generating: 'Generating…',
  saved: 'Summary saved.',
  preview: 'Preview',
  period: 'Period',
  periodStart: 'From',
  periodEnd: 'To',
  sinceLastVisit: 'Since last visit',
  history: 'Past summaries',
  recordVisit: 'Record visit today',
  visitRecorded: 'Visit recorded.',
  lastVisit: (d: string) => `Last visit: ${d}`,
  noVisit: 'No visit recorded yet',
  sections: {
    changes: 'Medicine changes in this period',
    current: 'Current medicines',
    adherence: 'Doses taken (reported)',
    symptoms: 'Symptom trends',
    flags: 'Flags',
    questions: 'Questions for the clinician',
  },
  header: {
    age: (n: number) => `Age ${n}`,
    period: 'Period',
    generated: 'Generated',
    by: 'By',
  },
  cols: {
    date: 'Date',
    medicine: 'Medicine',
    change: 'Change',
    detail: 'Detail',
    dose: 'Dose',
    schedule: 'Schedule',
    type: 'Type',
    rate: 'Taken',
    symptom: 'Symptom',
    firstSeen: 'First seen',
    days: 'Days',
    worst: 'Worst',
    trend: 'Trend',
    flag: 'Flag',
    severity: 'Severity',
    status: 'Status',
    note: 'Reviewer note',
  },
  overall: (rate: string, given: number, total: number) =>
    `Overall: ${rate} (${given} of ${total} doses, reported)`,
  noRows: 'None in this period.',
  more: (n: number) => `+${n} more`,
  trend: { better: 'Better', same: 'Same', worse: 'Worse' },
  severityWords: ['None', 'A little', 'Some', 'A lot'],
};
