export const qk = {
  profile: (id: string) => ['profile', id] as const,
  org: (id: string) => ['org', id] as const,
  alerts: (userId: string) => ['alerts', userId] as const,
  overview: (scope: string) => ['overview', scope] as const,
  patient: (id: string) => ['patient', id] as const,
  medications: (patientId: string) => ['medications', patientId] as const,
  changes: (patientId: string) => ['changes', patientId] as const,
  dosesDay: (patientId: string, date: string) => ['doses', patientId, 'day', date] as const,
  doses: (patientId: string, from: string, to: string) => ['doses', patientId, from, to] as const,
  adherenceDaily: (patientId: string, from: string, to: string) =>
    ['adherenceDaily', patientId, from, to] as const,
  symptomLogs: (patientId: string, from: string) => ['symptomLogs', patientId, from] as const,
  symptomLogDay: (patientId: string, date: string) => ['symptomLog', patientId, date] as const,
  template: (patientId: string) => ['template', patientId] as const,
  flags: (patientId: string) => ['flags', patientId] as const,
  inbox: () => ['inbox'] as const,
  consents: (patientId: string) => ['consents', patientId] as const,
  links: (patientId: string) => ['links', patientId] as const,
  summaries: (patientId: string) => ['summaries', patientId] as const,
  staff: () => ['staff'] as const,
  team: () => ['team'] as const,
  invitations: () => ['invitations'] as const,
  catalog: () => ['catalog'] as const,
  dashboard: () => ['dashboard'] as const,
  audit: (filters: string) => ['audit', filters] as const,
  pilot: (from: string, to: string) => ['pilot', from, to] as const,
};
